### ISSUE TITLE
#create in PostsController leads to a Forbidden Attribute Error

### ISSUE THREAD

**Issue by AudreyJones** [learn-co-curriculum/refresher-on-mvc#10] opened 2019-05-03 18:06 UTC
The way #create is written in PostsController leads to a Forbidden Attribute Error, unless a post's attributes are permitted:
Written as:
`def create
	  @post = Post.new(params)
          @post.save
	  redirect_to post_path(@post)
end`

Should be: (to be visible in browser)
`def create
	  @post = Post.new(params.require(:post).permit(:title,:description))
	  @post.save
	  redirect_to post_path(@post)
end`

**Comment by drakeltheryuujin** [comment] 2019-10-03 16:13
Hi @AudreyJones,

This issue looks like it may have been opened on the wrong repo, so I'm going to close it for now. If you can let us know which lesson this was intended for, we can take another look!

Thanks for your contribution!

**Closed as completed by drakeltheryuujin** 2019-10-03 16:13 UTC
